version: '3'
services:
        web:
                container_name: web
                build: .
                ports:
                  - "8000:8000"
                volumes:
                - static_volume:/app/staticfiles
                - media_volume:/app/mediafiles
                command: >
                          sh -c "python manage.py collectstatic --noinput &&
                          gunicorn --bind 0.0.0.0:8000 djangoProject.wsgi:application"
        nginx:
                build: ./nginx
                container_name: nginx
                depends_on:
                        - web
                volumes:
                        - static_volume:/app/staticfiles
                        - media_volume:/app/media
                ports:
                  - "80:80"
volumes:
  media_volume:
  static_volume:
