version: '3'

services:
        django:
                container_name: djando_container
                build: .
                ports:
                - "1234:1234"
                volumes:
                - static_volume:/staticfiles
                - media_volume:/mediafiles
