version: '3'
services:
        web:
                container_name: web
                build: .
                ports:
                - "8000:8000"
                volumes:
                - static_volume:/app/staticfiles
                - media_volume:/app/mediafiles
                command: >
                          sh -c "python manage.py collectstatic --noinput && 
                          gunicorn --bind 0.0.0.0:8000 djangoProject.wsgi:application"
        nginx:
                build: ./nginx
                container_name: nginx
                links:
                        - web
                depends_on:
                        - web
                volumes:
                        - static_volume:/app/staticfiles
                        - media_volume:/app/media
                ports:
                        - "80:80"
        sqlite3:
                image: nouchka/sqlite3:latest
                container_name: db_container
                stdin_open: true
                tty: true
                volumes:
                      - ./db:/root/db/
volumes:
  media_volume:
  static_volume: