version: '3'
services:
        web:
                container_name: web
                build: .
                ports:
                - "8078:8078"
                volumes:
                - static_volume:/app/staticfiles
                - media_volume:/app/mediafiles
                command: >
                          sh -c "python manage.py collectstatic --noinput && 
                          gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8000"
        nginx:
                build: ./nginx
                container_name: nginx
                links:
                        - web
                depends_on:
                        - web
                volumes:
                        - static_volume:/app/staticfiles
                        - media_volume:/app/media
                ports:
                        - "80:80"
volumes:
  media_volume:
  static_volume:
