# Generated by Django 4.2 on 2023-04-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('age', models.SmallIntegerField()),
                ('date_of_born', models.DateField()),
            ],
        ),
    ]
