# Generated by Django 4.2 on 2023-04-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_my_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_model',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='my_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
